version: '3.8'

services:
  # Nome do serviço da sua aplicação
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual ('.')
    build: .
    
    # Nome do container (opcional, mas útil para identificar)
    container_name: api
    
    # O comando para iniciar a aplicação.
    # Ele sobrescreve o CMD do Dockerfile, o que é útil para desenvolvimento.
    # O --reload faz com que o servidor reinicie a cada mudança no código.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    
    # Mapeia o diretório atual do seu computador para o diretório /app dentro do contêiner.
    # Isso garante que as alterações no código local sejam refletidas no contêiner.
    volumes:
      - .:/app

    # Mapeia a porta 8000 do contêiner para a porta 8000 do seu computador.
    ports:
      - "8000:8000"
